repos:
  - repo: local
    hooks:
      - id: lint
        name: lint all
        entry: poetry run poe lint-fmt
        language: system
        pass_filenames: false
        always_run: true
      - id: type-lint
        name: mypy lint
        entry: poetry run poe lint-typing
        language: system
        pass_filenames: false
        always_run: true
      - id: test
        name: pytest
        description: Runs the pytest suite for this project
        entry: poetry run poe test
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
